In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/2000-16-traffic-flow-england-scotland-wales/accidents_2012_to_2014.csv
/kaggle/input/2000-16-traffic-flow-england-scotland-wales/accidents_2009_to_2011.csv
/kaggle/input/2000-16-traffic-flow-england-scotland-wales/accidents_2005_to_2007.csv
/kaggle/input/2000-16-traffic-flow-england-scotland-wales/accident_coords_update.ipynb
/kaggle/input/2000-16-traffic-flow-england-scotland-wales/ukTrafficAADF.csv
/kaggle/input/2000-16-traffic-flow-england-scotland-wales/Areas.shp
/kaggle/input/2000-16-traffic-flow-england-scotland-wales/Local_Authority_Districts_Dec_2016.geojson


In [2]:
dataset1=pd.read_csv('/kaggle/input/2000-16-traffic-flow-england-scotland-wales/accidents_2005_to_2007.csv')
#dataset2=pd.read_csv('/kaggle/input/2000-16-traffic-flow-england-scotland-wales/accidents_2009_to_2011.csv')
#dataset3=pd.read_csv('/kaggle/input/2000-16-traffic-flow-england-scotland-wales/accidents_2012_to_2014.csv')

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3552: DtypeWarning: Columns (31) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [3]:
dataset1.info()
#dataset2.info()
#dataset3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 570011 entries, 0 to 570010
Data columns (total 33 columns):
 #   Column                                       Non-Null Count   Dtype  
---  ------                                       --------------   -----  
 0   Accident_Index                               570011 non-null  object 
 1   Location_Easting_OSGR                        569910 non-null  float64
 2   Location_Northing_OSGR                       569910 non-null  float64
 3   Longitude                                    569910 non-null  float64
 4   Latitude                                     569910 non-null  float64
 5   Police_Force                                 570011 non-null  int64  
 6   Accident_Severity                            570011 non-null  int64  
 7   Number_of_Vehicles                           570011 non-null  int64  
 8   Number_of_Casualties                         570011 non-null  int64  
 9   Date                                         570011 non-nul

In [4]:
dataset1.head()

Accident_Index  Location_Easting_OSGR  Location_Northing_OSGR  Longitude  \
0  200501BS00001               525680.0                178240.0  -0.191170   
1  200501BS00002               524170.0                181650.0  -0.211708   
2  200501BS00003               524520.0                182240.0  -0.206458   
3  200501BS00004               526900.0                177530.0  -0.173862   
4  200501BS00005               528060.0                179040.0  -0.156618   

    Latitude  Police_Force  Accident_Severity  Number_of_Vehicles  \
0  51.489096             1                  2                   1   
1  51.520075             1                  3                   1   
2  51.525301             1                  3                   2   
3  51.482442             1                  3                   1   
4  51.495752             1                  3                   1   

   Number_of_Casualties        Date  ...  \
0                     1  04/01/2005  ...   
1                     1  05/01/2005  ...   
2                     1  06/01/2005  ...   
3                     1  07/01/2005  ...   
4                     1  10/01/2005  ...   

       Pedestrian_Crossing-Physical_Facilities  \
0                               Zebra crossing   
1  Pedestrian phase at traffic signal junction   
2        No physical crossing within 50 meters   
3        No physical crossing within 50 meters   
4        No physical crossing within 50 meters   

                          Light_Conditions          Weather_Conditions  \
0           Daylight: Street light present  Raining without high winds   
1  Darkness: Street lights present and lit     Fine without high winds   
2  Darkness: Street lights present and lit     Fine without high winds   
3           Daylight: Street light present     Fine without high winds   
4        Darkness: Street lighting unknown     Fine without high winds   

  Road_Surface_Conditions  Special_Conditions_at_Site  Carriageway_Hazards  \
0                Wet/Damp                        None                 None   
1                     Dry                        None                 None   
2                     Dry                        None                 None   
3                     Dry                        None                 None   
4                Wet/Damp                        None                 None   

  Urban_or_Rural_Area  Did_Police_Officer_Attend_Scene_of_Accident  \
0                   1                                          Yes   
1                   1                                          Yes   
2                   1                                          Yes   
3                   1                                          Yes   
4                   1                                          Yes   

   LSOA_of_Accident_Location  Year  
0                  E01002849  2005  
1                  E01002909  2005  
2                  E01002857  2005  
3                  E01002840  2005  
4                  E01002863  2005  

[5 rows x 33 columns]

In [8]:
dataset1.columns

Index(['Accident_Index', 'Location_Easting_OSGR', 'Location_Northing_OSGR',
       'Longitude', 'Latitude', 'Police_Force', 'Accident_Severity',
       'Number_of_Vehicles', 'Number_of_Casualties', 'Date', 'Day_of_Week',
       'Time', 'Local_Authority_(District)', 'Local_Authority_(Highway)',
       '1st_Road_Class', '1st_Road_Number', 'Road_Type', 'Speed_limit',
       'Junction_Detail', 'Junction_Control', '2nd_Road_Class',
       '2nd_Road_Number', 'Pedestrian_Crossing-Human_Control',
       'Pedestrian_Crossing-Physical_Facilities', 'Light_Conditions',
       'Weather_Conditions', 'Road_Surface_Conditions',
       'Special_Conditions_at_Site', 'Carriageway_Hazards',
       'Urban_or_Rural_Area', 'Did_Police_Officer_Attend_Scene_of_Accident',
       'LSOA_of_Accident_Location', 'Year'],
      dtype='object')

In [9]:
dataset1.Police_Force.unique()

array([ 1, 48,  3,  4,  5,  6,  7, 10, 11, 12, 13, 14, 16, 17, 20, 21, 22,
       23, 30, 31, 32, 33, 34, 35, 36, 37, 40, 41, 42, 43, 44, 45, 46, 47,
       50, 52, 53, 54, 55, 60, 61, 62, 63, 91, 92, 93, 94, 95, 96, 97, 98])

In [10]:
dataset1.Date.head()

0    04/01/2005
1    05/01/2005
2    06/01/2005
3    07/01/2005
4    10/01/2005
Name: Date, dtype: object

In [11]:
dataset1.Day_of_Week.head()

0    3
1    4
2    5
3    6
4    2
Name: Day_of_Week, dtype: int64

In [12]:
dataset1.Time.head()

0    17:42
1    17:36
2    00:15
3    10:35
4    21:13
Name: Time, dtype: object

In [14]:
dataset1['Local_Authority_(District)'].unique()

array([ 12,   1,  11, 570,   5,   8,   4,   3,   2,   9,  28,  31,  30,
        27,  24,  13,  17,  57,  26,  29,  25,  32,  14,  16,  15,  20,
        10,  21,   7,  19,   6,  18,  23,  22,  65,  61,  62,  64,  60,
        63,  71,  74,  76,  70,  79,  85,  83,  84,  73,  75,  80,  77,
        82,  72,  95,  93,  91,  90,  92, 102, 104, 107, 101, 106, 112,
       110, 109, 114, 100, 120, 128, 124, 126, 122, 123, 127, 121, 147,
       150, 148, 140, 145, 142, 146, 149, 144, 143, 141, 168, 165, 163,
       164, 160, 162, 166, 161, 189, 186, 180, 187, 182, 181, 184, 185,
       204, 202, 200, 203, 206, 211, 213, 210, 215, 233, 232, 231, 228,
       240, 241, 243, 245, 300, 309, 307, 303, 305, 306, 302, 257, 255,
       256, 253, 251, 250, 254, 252, 258, 276, 277, 273, 278, 270, 274,
       279, 285, 282, 280, 281, 283, 284, 293, 294, 292, 290, 291, 324,
       320, 321, 329, 325, 327, 322, 328, 323, 344, 340, 345, 341, 347,
       346, 342, 343, 354, 355, 353, 351, 356, 350, 352, 364, 36

In [15]:
dataset1['Local_Authority_(Highway)'].unique()

array(['E09000020', 'E09000033', 'E09000013', 'E09000001', 'E09000030',
       'E09000028', 'E09000012', 'E09000019', 'E09000007', 'E09000022',
       'E09000005', 'E09000014', 'E09000003', 'E09000009', 'E09000027',
       'E09000031', 'E09000025', 'EHEATHROW', 'E09000017', 'E09000015',
       'E09000018', 'E09000010', 'E09000026', 'E09000002', 'E09000016',
       'E09000008', 'E09000032', 'E09000029', 'E09000023', 'E09000006',
       'E09000011', 'E09000004', 'E09000021', 'E09000024', 'E10000006',
       'E06000009', 'E10000017', 'E06000008', 'E08000015', 'E08000014',
       'E08000012', 'E08000011', 'E08000013', 'E08000003', 'E08000004',
       'E08000006', 'E08000002', 'E08000005', 'E08000009', 'E08000008',
       'E08000007', 'E08000010', 'E08000001', 'E06000050', 'E06000007',
       'E06000006', 'E06000049', 'E08000021', 'E08000024', 'E08000022',
       'E06000048', 'E08000020', 'E08000023', 'E06000047', 'E06000005',
       'E06000014', 'E10000023', 'E08000035', 'E08000033', 'E080

In [16]:
dataset1['1st_Road_Class'].head()

0    3
1    4
2    5
3    3
4    6
Name: 1st_Road_Class, dtype: int64

In [17]:
dataset1['1st_Road_Class'].unique()

array([3, 4, 5, 6, 1, 2])

In [18]:
dataset1['1st_Road_Number'].head()

0    3218
1     450
2       0
3    3220
4       0
Name: 1st_Road_Number, dtype: int64

In [19]:
dataset1['Road_Type'].head()

0    Single carriageway
1      Dual carriageway
2    Single carriageway
3    Single carriageway
4    Single carriageway
Name: Road_Type, dtype: object

In [20]:
dataset1['Road_Type'].unique()

array(['Single carriageway', 'Dual carriageway', 'One way street',
       'Roundabout', 'Slip road', 'Unknown'], dtype=object)

In [22]:
dataset1.Speed_limit.unique()

array([30, 40, 50, 20, 60, 70, 10, 15])

In [25]:
dataset1['Junction_Control'].head()

0                         NaN
1    Automatic traffic signal
2                         NaN
3                         NaN
4                         NaN
Name: Junction_Control, dtype: object

In [26]:
dataset1['Junction_Control'].unique()

array([nan, 'Automatic traffic signal', 'Giveway or uncontrolled',
       'Stop Sign', 'Authorised person'], dtype=object)

In [28]:
dataset1['2nd_Road_Class'].unique()

array([-1,  5,  6,  4,  3,  1,  2])

In [30]:
dataset1['Pedestrian_Crossing-Human_Control'].unique()

array(['None within 50 metres', 'Control by other authorised person',
       'Control by school crossing patrol', nan], dtype=object)

In [31]:
dataset1['Pedestrian_Crossing-Physical_Facilities'].unique()

array(['Zebra crossing', 'Pedestrian phase at traffic signal junction',
       'No physical crossing within 50 meters', 'Central refuge',
       'non-junction pedestrian crossing', 'Footbridge or subway', nan],
      dtype=object)

In [33]:
dataset1.Light_Conditions.unique()

array(['Daylight: Street light present',
       'Darkness: Street lights present and lit',
       'Darkness: Street lighting unknown',
       'Darkness: Street lights present but unlit',
       'Darkeness: No street lighting'], dtype=object)

In [35]:
dataset1['Weather_Conditions'].unique()

array(['Raining without high winds', 'Fine without high winds', 'Unknown',
       'Snowing without high winds', 'Other', 'Fine with high winds',
       'Raining with high winds', 'Fog or mist',
       'Snowing with high winds', nan], dtype=object)

In [37]:
dataset1['Road_Surface_Conditions'].unique()

array(['Wet/Damp', 'Dry', 'Frost/Ice', 'Snow',
       'Flood (Over 3cm of water)', nan], dtype=object)

In [39]:
dataset1['Special_Conditions_at_Site'].unique()

array(['None', 'Ol or diesel', 'Roadworks',
       'Auto traffic signal partly defective', 'Road surface defective',
       'Auto traffic singal out',
       'Permanent sign or marking defective or obscured', 'Mud', nan],
      dtype=object)

In [41]:
dataset1['Carriageway_Hazards'].unique()

array(['None', 'Other object in carriageway',
       'Pedestrian in carriageway (not injured)',
       'Dislodged vehicle load in carriageway',
       'Involvement with previous accident',
       'Any animal (except a ridden horse)', nan], dtype=object)

In [42]:
dataset1['Urban_or_Rural_Area'].unique()

array([1, 2, 3])

In [43]:
dataset1['Did_Police_Officer_Attend_Scene_of_Accident'].unique()

array(['Yes', 'No', nan], dtype=object)

In [44]:
dataset1['LSOA_of_Accident_Location'].head()

0    E01002849
1    E01002909
2    E01002857
3    E01002840
4    E01002863
Name: LSOA_of_Accident_Location, dtype: object

In [5]:
dataset1.isnull().sum()

Accident_Index                                      0
Location_Easting_OSGR                             101
Location_Northing_OSGR                            101
Longitude                                         101
Latitude                                          101
Police_Force                                        0
Accident_Severity                                   0
Number_of_Vehicles                                  0
Number_of_Casualties                                0
Date                                                0
Day_of_Week                                         0
Time                                               67
Local_Authority_(District)                          0
Local_Authority_(Highway)                           0
1st_Road_Class                                      0
1st_Road_Number                                     0
Road_Type                                           0
Speed_limit                                         0
Junction_Detail             

In [ ]:
#Objectif : mis en place d'un model prédictif sur la sévérité d'un accident

# donnée de sortie (Y) : Accident_Severity

# données sans intérêt : Accident_Index , Local_Authority_(District) , Local_Authority_(Highway) , 1st_Road_Number , Junction_Detail ,
#                        2nd_Road_Number , Year

# données d'intérêt (X) : Police_Force *infos géo région* , Number_of_Vehicles , Number_of_Casualties , Date , Day_of_Week , Time ,
#                         1st_Road_Class , Road_Type , Speed_limit , Pedestrian_Crossing-Human_Control , Pedestrian_Crossing-Physical_Facilities ,
#                         Light_Conditions , Weather_Conditions , Road_Surface_Conditions , Special_Conditions_at_Site , Carriageway_Hazards ,
#                         Urban_or_Rural_Area , Did_Police_Officer_Attend_Scene_of_Accident , 

# données je-sais-pas-quoi-en-faire : Junction_Control , LSOA_of_Accident_Location
'''
TODO :  _vérifier si les 2nd_Road_Class == -1 correspondent à Junction_Control == Null ??
        _ count() les lignes dont 1 attribut est renseigné 'unknown'
'''